[package]
name = "valgrind_bindings"
description = "Rust bindings for valgrind memcheck macros"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2.54"
pkg-config = "0.3.32"